controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - rotator_1_joint
      - rotator_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position